### ISSUE TITLE
Non-deterministic behaviour and bug in choice of next removal

### ISSUE THREAD

**Issue by flocko-motion** [PaoloPellizzoni/CurvatureEnhancedMeshSimplification#1]
![Screenshot_20201110_171507](https://user-images.githubusercontent.com/43704929/98704571-18452180-237d-11eb-867d-618162e0ed2a.png)
![Screenshot_20201110_171452](https://user-images.githubusercontent.com/43704929/98704576-19764e80-237d-11eb-8406-72c8192d946d.png)
![Screenshot_20201110_171425](https://user-images.githubusercontent.com/43704929/98704578-19764e80-237d-11eb-9113-e1339d772e57.png)

These three images show the ouput of the algorithm for the same input data and the same parameters. Variations happen when adding ANY line of code at ANY position in the program. The reason for this is, that java object hashes are used as pseudo random numbers:

    public int compareTo(EdgePair ep)
    {
        if(Math.abs(this.error - ep.error) > 10e-15)
            return (this.error - ep.error)>0 ? 1 : -1;
        return e.hashCode() - ep.hashCode(); //random
    }

I propose changing 
```return e.hashCode() - ep.hashCode(); //random```
to
```return e.hashCode() - ep.e.hashCode(); //random```
That would make the results absolutely deterministic as the edge hash is calculated from the vertex coordinates (while the EdgePair hash is calculated internally by java - probably from the memory location of the object).

The second question is: why does the algorithm sometimes choose to remove these chunks from the mesh? This doesn't seem to be correct behavior and looks like a bug. I will further investigate the issue - any help is highly appreciated, though.

**Comment by PaoloPellizzoni** [comment]
Your proposal is definitely correct, I will implement it in the future.
Concerning the second issue, I noticed the same behaviour but I couldn't figure out the bug. It may also be due to some degeneracy in the triangles that has to be checked before removing edges. If you find any insight please let me know and I'll try and fix this issue.

**Comment by flocko-motion** [comment]
Problem solved :)
